language: node_js
node_js: node
branches:
  only: master
script: npm run build
after_script:
  - cd _book
  - git init
  - git config user.name "sm-bot"
  - git config user.email "bot@sm.cn"
  - git add .
  - git commit -m 'Boring work...'
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/sm-fe/month.git" master:gh-pages
